server:
  port: 8080

spring:
  application:
    name: migrator

  datasource:
    url: jdbc:postgresql://localhost:5440/migration_db
    username: my_user
    password: 12345

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true

  liquibase:
    change-log: db/migration/changelog/0001_changelog.xml

file:
  properties:
    allowed-extensions:
      - cvs
    max-size: 100